### ISSUE TITLE
Possible NullPointerException

### ISSUE THREAD

**Issue by ddolgushin** [pschoepf/naturalbreaks#1]
Hello, Philipp! Thank you for your work, it's great. I've made a port of this code to C# (https://github.com/ddolgushin/stats) and noticed one bug here:

https://github.com/pschoepf/naturalbreaks/blob/235860c86b5d6c53fc45fe31438123c0fdf5e6fe/src/main/java/de/pschoepf/naturalbreaks/JenksFisher.java#L290

The problem is that the "breaksArray" isn't initialized but is expected to have "sortedUniqueValueCounts.length" slots. So the solution might be the preliminary initialization of this array just before the loop.

**Comment by pschoepf** [comment]
Thanks, bug has been fixed
